export const INDIAN_UNIVERSITIES = [
  "Anna University",
  "IIT Madras (Indian Institute of Technology Madras)",
  "IIT Bombay (Indian Institute of Technology Bombay)",
  "IIT Delhi (Indian Institute of Technology Delhi)",
  "IIT Kanpur (Indian Institute of Technology Kanpur)",
  "IIT Kharagpur (Indian Institute of Technology Kharagpur)",
  "IIT Roorkee (Indian Institute of Technology Roorkee)",
  "IIT Guwahati (Indian Institute of Technology Guwahati)",
  "NIT Trichy (National Institute of Technology Tiruchirappalli)",
  "NIT Surathkal (National Institute of Technology Karnataka)",
  "NIT Warangal (National Institute of Technology Warangal)",
  "VIT (Vellore Institute of Technology)",
  "SRM Institute of Science and Technology",
  "Amrita Vishwa Vidyapeetham",
  "SASTRA Deemed University",
  "Kalasalingam Academy of Research and Education",
  "Karunya Institute of Technology and Sciences",
  "Bharathiar University",
  "Bharathidasan University",
  "Madurai Kamaraj University",
  "Manonmaniam Sundaranar University",
  "Periyar University",
  "Annamalai University",
  "Pondicherry University",
  "University of Madras",
  "PSG College of Technology",
  "Coimbatore Institute of Technology (CIT)",
  "Amrita School of Engineering",
  "SNS College of Technology",
  "SNS College of Engineering",
  "Kumaraguru College of Technology",
  "Kongu Engineering College",
  "Bannari Amman Institute of Technology",
  "Sona College of Technology",
  "Thiagarajar College of Engineering",
  "Government College of Technology, Coimbatore",
  "KPR Institute of Engineering and Technology",
  "Sri Ramakrishna Engineering College",
  "Sri Krishna College of Engineering and Technology",
  "Hindusthan College of Engineering and Technology",
  "Vellalar College of Engineering and Technology",
  "Mepco Schlenk Engineering College",
  "Sathyabama Institute of Science and Technology",
  "Hindustan Institute of Technology and Science",
  "St. Joseph's College of Engineering",
  "SSN College of Engineering",
  "Panimalar Engineering College",
  "Rajalakshmi Engineering College",
  "RMK Engineering College",
  "Vel Tech Rangarajan Dr. Sagunthala R&D Institute of Science and Technology",
  "Saveetha Institute of Medical and Technical Sciences",
  "BITS Pilani (Birla Institute of Technology and Science)",
  "Manipal Academy of Higher Education",
  "Jawaharlal Nehru University (JNU)",
  "University of Delhi (DU)",
  "Banaras Hindu University (BHU)",
  "University of Calcutta",
  "University of Mumbai",
  "University of Hyderabad",
  "Jamia Millia Islamia",
  "Aligarh Muslim University (AMU)",
  "Jadavpur University",
  "Savitribai Phule Pune University",
  "University of Kerala",
  "Cochin University of Science and Technology (CUSAT)",
  "Osmania University",
  "JNTU Hyderabad (Jawaharlal Nehru Technological University)",
  "JNTU Kakinada (Jawaharlal Nehru Technological University)",
  "JNTU Anantapur (Jawaharlal Nehru Technological University)",
  "Andhra University",
  "Visvesvaraya Technological University (VTU)",
  "Manipal Institute of Technology",
  "Amity University",
  "Lovely Professional University (LPU)",
  "Chandigarh University",
  "Thapar Institute of Engineering and Technology",
  "Birla Institute of Technology, Mesra",
  "Indian Institute of Science (IISc), Bangalore",
  "TATA Institute of Fundamental Research (TIFR)",
  "ISI Kolkata (Indian Statistical Institute)",
  "IIIT Hyderabad",
  "IIIT Bangalore",
  "Dhirubhai Ambani Institute of Information and Communication Technology (DA-IICT)",
  "University of Rajasthan",
  "Panjab University",
  "University of Lucknow",
  "Allahabad University",
  "Patna University",
  "Gauhati University",
  "Utkal University",
  "Mysore University",
  "Karnatak University",
  "Bangalore University",
  "Gulbarga University",
  "Kuvempu University",
  "Mangalore University",
  "Calicut University",
  "Mahatma Gandhi University, Kottayam",
  "Kannur University",
  "Gujarat University",
  "Sardar Patel University",
  "Maharaja Sayajirao University of Baroda",
  "Rajasthan Technical University",
  "Kurukshetra University",
  "Guru Jambheshwar University of Science and Technology",
  "Deenbandhu Chhotu Ram University of Science and Technology",
  "YMCA University of Science and Technology",
  "Indraprastha Institute of Information Technology (IIIT Delhi)",
  "Delhi Technological University (DTU)",
  "Netaji Subhas University of Technology (NSUT)",
  "Guru Gobind Singh Indraprastha University (GGSIPU)",
  "Shiv Nadar University",
  "Bennett University",
  "OP Jindal Global University",
  "Ashoka University",
  "Plaksha University",
  "Krea University",
  "Flame University",
  "Chitkara University",
  "PEC University of Technology",
  "National Institute of Design (NID)",
  "National Institute of Fashion Technology (NIFT)",
  "National Law School of India University (NLSIU)",
  "National Law University (NLU)",
  "Indian School of Business (ISB)",
  "IIM Ahmedabad",
  "IIM Bangalore",
  "IIM Calcutta",
  "IIM Lucknow",
  "IIM Kozhikode",
  "IIM Indore",
  "IIM Trichy",
  "IIM Udaipur",
  "IIM Shillong",
  "IIM Ranchi",
  "IIM Raipur",
  "IIM Rohtak",
  "IIM Kashipur",
  "IIM Amritsar",
  "IIM Bodh Gaya",
  "IIM Jammu",
  "IIM Nagpur",
  "IIM Sambalpur",
  "IIM Sirmaur",
  "IIM Visakhapatnam",
  "XLRI - Xavier School of Management",
  "S. P. Jain Institute of Management and Research (SPJIMR)",
  "Management Development Institute (MDI)",
  "Indian Institute of Foreign Trade (IIFT)",
  "Symbiosis International University",
  "Narsee Monjee Institute of Management Studies (NMIMS)",
  "Xavier Institute of Management, Bhubaneswar (XIMB)",
  "Institute of Management Technology (IMT)",
  "Fore School of Management",
  "Birla Institute of Management Technology (BIMTECH)",
  "Goa Institute of Management (GIM)",
  "Loyola Institute of Business Administration (LIBA)",
  "Great Lakes Institute of Management",
  "Bharathidasan Institute of Management (BIM)",
  "PSG Institute of Management",
  "T. A. Pai Management Institute (TAPMI)",
  "Institute of Rural Management Anand (IRMA)",
  "MICA (Mudra Institute of Communications, Ahmedabad)",
  "Indian Institute of Mass Communication (IIMC)",
  "Film and Television Institute of India (FTII)",
  "Satyajit Ray Film and Television Institute (SRFTI)",
  "National School of Drama (NSD)",
  "Indira Gandhi National Open University (IGNOU)",
  "Tamil Nadu Open University",
  "YCMOU (Yashwantrao Chavan Maharashtra Open University)",
  "Dr. B.R. Ambedkar Open University",
  "Netaji Subhas Open University",
  "Karnataka State Open University",
  "Madurai Kamaraj University DDE",
  "Annamalai University DDE",
  "Bharathiar University SDE",
  "others"
] as const;
